name: Scrape Latest data

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Scrape latest data
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: npm ci
      - name: Scrape
        run: npm start
      - name: Commit and push changes
        run: |-
        git config user.name "Scraper"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push